"""Inital table setup

Revision ID: 5b456aca87c6
Revises:
Create Date: 2026-01-26 23:24:44.077669

"""

from typing import Sequence, Union

import alembic.op as op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b456aca87c6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ambulances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("assigned_patient_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hospitals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("bed_capacity", sa.Integer(), nullable=False),
        sa.Column("used_beds", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patient_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=True),
        sa.Column("ambulance_id", sa.Uuid(), nullable=True),
        sa.Column("travel_time_minutes", sa.Integer(), nullable=True),
        sa.Column("time_left_minutes", sa.Integer(), nullable=True),
        sa.Column("time_to_hospital_minutes", sa.Integer(), nullable=False),
        sa.Column("patient_registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requires_urgent_transport", sa.Boolean(), nullable=False),
        sa.Column("optimized_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("time_to_hospital_minutes", sa.Integer(), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("patients")
    op.drop_table("patient_assignments")
    op.drop_table("hospitals")
    op.drop_table("ambulances")
    # ### end Alembic commands ###
