"""Added patient name and status

Revision ID: e2f2d1adb268
Revises: 5b456aca87c6
Create Date: 2026-03-21 22:26:35.436030

"""

from typing import Sequence, Union

import alembic.op as op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2f2d1adb268"
down_revision: Union[str, Sequence[str], None] = "5b456aca87c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patients", sa.Column("name", sa.String(), nullable=True))
    op.add_column("patients", sa.Column("status", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "status")
    op.drop_column("patients", "name")
    # ### end Alembic commands ###
